feat(selectAll): hide Select All checkbox, expose selectAll and deselectAll methods
Neovici/cosmoz-omnitable pull request #545
Opened 2022-10-25 08:50 UTC by angrynerds-weronika

[AB#8033](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/8033)

Connected Cosmoz PR:

2022-10-25 09:20 UTC, megheaiulian requested changes

2022-10-25 09:35 UTC, megheaiulian commented on lib/render-header.js
> +			<div class="headerDots"><span>...</span></div>
We could also go with a property for a different template.

2022-10-26 07:34 UTC, angrynerds-weronika commented on lib/render-header.js
> +			<div class="headerDots"><span>...</span></div>
Done

2022-10-26 09:32 UTC, megheaiulian approved these changes
This looks good to me!

Now we use headerDots instead of the selector all but I think that we need to actually replace the select all button with the omnitable settings dropdown button and style it like in the design.

We can merge this and do the above in another PR.

2022-10-26 12:30 UTC, merged