feat(treenode column): passing along three new values
Neovici/cosmoz-omnitable pull request #559
Opened 2023-01-31 13:29 UTC by JockeCK

Needed for treenode column change [#92](https://github.com/Neovici/cosmoz-omnitable-treenode-column/pull/92)

2023-02-15 13:19 UTC, megheaiulian reviewed
@cristinecula It sucks that we need to do this. 
Couldn't we have a way for dom columns to expose their own properties that should be passed to render? Maybe the renderCell, renderHeader etc.. should have easy access the full column object.

2023-02-23 05:10 UTC, megheaiulian requested changes

2023-02-23 05:10 UTC, megheaiulian commented on lib/use-dom-columns.js
To avoid listing all the possible properties of all columns in one place we should refactor this a bit to call a optional function implementation `getConfig` on each column. 

```suggestion
...column.getConfig?.(column),
```

In that case in treenode columns we can implement this: 
```
 getConfig(column) {
 return {
limit: column.limit,
hideFromRoot: column.hideFromRoot
....etc
}
}

```

2023-02-23 09:57 UTC, JockeCK commented on lib/use-dom-columns.js
ok, pushed change.

2023-02-23 13:58 UTC, megheaiulian commented on lib/use-dom-columns.js
> +			limit: column.limit,
We can remove this if we have column.getConfig

2023-02-23 13:59 UTC, megheaiulian commented on lib/use-dom-columns.js
> +			hideFromRoot: column.hideFromRoot,
and this too

2023-02-28 08:44 UTC, megheaiulian commented on lib/use-dom-columns.js
> +			limit: column.limit,
@JockeCK Can we remove this lines ? only `...column.getConfig?.(column),` is needed.

2023-03-02 10:18 UTC, JockeCK commented on lib/use-dom-columns.js
> +			limit: column.limit,
Of course, sorry for late replies.

2023-03-06 08:37 UTC, megheaiulian approved these changes

2023-03-06 08:38 UTC, merged