Link-underline-removal
Neovici/cosmoz-omnitable pull request #561
Opened 2023-02-03 15:46 UTC by CarloBar1

2023-02-07 19:15 UTC, cristinecula commented
Please include reference to issue.

2023-02-13 15:22 UTC, cristinecula requested changes

2023-02-13 15:22 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		color: lightblue;
Are you sure you want to override the color style here?

2023-02-13 15:24 UTC, cristinecula requested changes

2023-02-13 15:24 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> -
SO many useless whitespace changes. Are they added by prettier? If not, please revert them.

2023-02-13 15:24 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		color: grey;
If you are going to set a color, you should use a variable, to enable customization.

2023-02-13 15:33 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		color: grey;
Is setting a color even necessary here?

2023-02-15 13:05 UTC, CarloBar1 commented on cosmoz-omnitable-styles.js
> -
I applied Prettier and it separates every selector's brackets with a whitespace - I just re-applied Prettier over the whole document now

2023-02-20 13:45 UTC, cristinecula requested changes
I would like to have this configurable. Can we add `--cosmoz-omnitable-link-decoration` and `--cosmoz-omnitable-link-decoration--hover` variables?

2023-02-20 13:45 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +	//The following code makes the link underlining appear only on mouseover
Comment is just explaining the obvious.
```suggestion
```

2023-02-20 14:58 UTC, CarloBar1 commented on cosmoz-omnitable-styles.js
> +	//The following code makes the link underlining appear only on mouseover
Comment deleted, decoration variabilized

2023-02-20 15:05 UTC, cristinecula requested changes

2023-02-20 15:05 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		text-decoration: none;
This should also use the css var.

2023-02-20 15:05 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		text-decoration: var(--cosmoz-omnitable-link-decoration, none);
Please keep the underline, as that is the default browser behaviour. We'll style it differently in frontend.
```suggestion
		text-decoration: var(--cosmoz-omnitable-link-decoration, underline);
```

2023-02-20 18:04 UTC, cristinecula requested changes

2023-02-20 18:04 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +	}
```suggestion
```

This sets the `text-decoration` to none, which is the opposite of what we want.

2023-03-16 11:41 UTC, cristinecula approved these changes

2023-03-16 11:41 UTC, merged