Feature 9162 rebased
Neovici/cosmoz-omnitable pull request #564
Opened 2023-02-08 15:02 UTC by CarloBar1

Rebased branch for [previous pull request](https://github.com/Neovici/cosmoz-omnitable/pull/560), as there were too many wrong commit messages

2023-02-13 15:21 UTC, cristinecula requested changes
Almost there.

2023-02-13 15:21 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		);
Are you sure that this works correctly? AFAIK `var` only takes 2 parameters, and you have 3.

2023-02-13 15:21 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		text-transform: var(--cosmoz-header-text-transform, uppercase);
You should include the component name in the css var, so it is clear when someone is reading the CSS the purpose of a certain variable.

```suggestion
		text-transform: var(--cosmoz-omnitable-header-text-transform, uppercase);
```

2023-02-15 10:40 UTC, CarloBar1 commented on cosmoz-omnitable-styles.js
> +		);
In the [CSS var() definition](https://developer.mozilla.org/en-US/docs/Web/CSS/var), it says that a var declaration can allow more than one fallback value after the first comma. It is though a bit unclear whether the fallback values are considered one after each other, so I just deleted those commas.

2023-02-16 11:14 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +		);
Please figure out how it is supposed to be written and update accordingly. Experiment with both variants and figure out which is doing the right thing.

2023-02-16 14:02 UTC, cristinecula requested changes

2023-02-16 14:02 UTC, cristinecula commented on cosmoz-omnitable-styles.js
> +	paper-input {
It should work the same if you defined these styles for the header containing element.
```suggestion
	[selector-for-header-container] {
```

Please try it out.

2023-02-16 14:02 UTC, cristinecula commented on lib/settings/cosmoz-omnitable-settings.js
> +						<circle cx="10" cy="6" r="2"></circle></svg>`
Please post a screenshot.

2023-02-16 14:04 UTC, CarloBar1 commented on lib/settings/cosmoz-omnitable-settings.js
> +						<circle cx="10" cy="6" r="2"></circle></svg>`
![image](https://user-images.githubusercontent.com/122988480/219386013-7a878b35-b32a-4813-b444-509ecd108284.png)

2023-02-16 14:07 UTC, CarloBar1 commented on lib/settings/cosmoz-omnitable-settings.js
> +						<circle cx="10" cy="6" r="2"></circle></svg>`
Right now it looks like this:
![image](https://user-images.githubusercontent.com/122988480/219386813-d7101fde-ebdb-4fd3-8596-517005d73283.png)

2023-02-16 14:12 UTC, CarloBar1 commented on cosmoz-omnitable-styles.js
> +	paper-input {
Included all in the .header-cell selector, and it works.

2023-02-17 11:57 UTC, merged