fix(footer): set max-toolbar-items when mini table is used
Neovici/cosmoz-omnitable pull request #634
Opened 2024-12-09 10:38 UTC by micaelagoffe

Set max-toolbar-items on cosmoz-bottom-bar when mini table is used

[AB#17737](https://dev.azure.com/neovici/Cosmoz3/_backlogs/backlog/UX/Stories/?workitem=17737)

2024-12-09 10:53 UTC, cristinecula requested changes

2024-12-09 10:53 UTC, cristinecula commented on lib/use-footer.js
> +		isMiniTable,
```suggestion
		maxToolbarItems,
```

2024-12-09 10:53 UTC, cristinecula commented on lib/use-footer.js
> +		isMiniTable = host.hasAttribute('mini');
This is not a great way to determine if the omnitable is in `mini` state. You should make use of [isMiniSize](https://github.com/Neovici/cosmoz-omnitable/blob/18c0da7d4dc8ffa8e11708f0fd529ab0271715b5/lib/use-mini.js#L5) and determine the number of toolbar items in the main hook.

```suggestion
      maxToolbarItems,
		} = host;
```

2024-12-09 10:54 UTC, cristinecula commented
Ideally the cosmoz-bottom-bar element would use intersection observers or some other mechanism to determine if it should show/hide the button.

2024-12-09 16:33 UTC, cristinecula requested changes

2024-12-09 16:33 UTC, cristinecula commented on lib/use-omnitable.js
> +		maxToolbarItems = host.hasAttribute('mini') && isMiniSize ? '0' : '',
Reading the `isMini` state from the `host` element is too indirect and will lead to confusion. Instead, you should alter the code in  `useMini` to provide this information as a flag.

https://github.com/Neovici/cosmoz-omnitable/blob/18c0da7d4dc8ffa8e11708f0fd529ab0271715b5/lib/use-mini.js#L3-L29

```js
  const hasMiniColumn =  !!miniColumn

	useEffect(() => {
		host.toggleAttribute('mini', hasMiniColumn);
	}, [hasMiniColumn]);

  return {
    isMini: hasMiniColumn && isMiniSize
  }
```

2024-12-09 16:33 UTC, cristinecula commented on lib/use-omnitable.js
> +		maxToolbarItems = host.hasAttribute('mini') && isMiniSize ? '0' : '',
```suggestion
		maxToolbarItems = isMini ? 0 : undefined, // should be a number or undefined
```

2024-12-09 16:33 UTC, cristinecula commented on lib/render-footer.js
> +		?max-toolbar-items=${!isEmpty(maxToolbarItems)}
`?prop` should only be used for boolean attributes, for number props you should use `.prop`. 

```suggestion
		.maxToolbarItems=${maxToolbarItems}
```

2024-12-10 10:15 UTC, micaelagoffe commented on lib/use-omnitable.js
> +		maxToolbarItems = host.hasAttribute('mini') && isMiniSize ? '0' : '',
After our discussion in slack I'm using ´'0' : undefined´, so I can keep the isEmpty check in render-footer.

2024-12-10 10:16 UTC, micaelagoffe commented on lib/render-footer.js
> +		?max-toolbar-items=${!isEmpty(maxToolbarItems)}
Keeping this change after our discussion in slack 🙂

2024-12-10 10:34 UTC, cristinecula approved these changes

2024-12-10 10:35 UTC, merged